"""add_preview_fields_to_jobs

Revision ID: e4d774550ce1
Revises: 0005
Create Date: 2026-06-01 08:55:49.036790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d774550ce1'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('preview_url', sa.String(length=500), nullable=True))
    op.add_column('jobs', sa.Column('thumb_url', sa.String(length=500), nullable=True))
    op.add_column('jobs', sa.Column('original_url', sa.String(length=500), nullable=True))
    op.drop_constraint('trends_template_id_fkey', 'trends', type_='foreignkey')
    op.create_foreign_key(None, 'trends', 'templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trends', type_='foreignkey')
    op.create_foreign_key('trends_template_id_fkey', 'trends', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.drop_column('jobs', 'original_url')
    op.drop_column('jobs', 'thumb_url')
    op.drop_column('jobs', 'preview_url')
    # ### end Alembic commands ###
